config/routes.rb
Rails.application.routes.draw do
  resources :coins, only: [:index, :create]
  get "reset", to: 'coins#reset'

  get "ping" => "ping#index", constraints: { ip: /::1|127\.0\.0\.1/ }

  root "coins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  class << self
    def heads
      where(heads: true).count
    end

    def tails
      where(heads: false).count
    end

    def flip
      new(heads: [true, false].sample)
    end

    def flip!
      flip.save!
    end
  end

  def to_s
    heads? ? "Head" : "Tail"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :get_coins, only: [:index, :create]

  def index
  end

  def create
    @coin = Coin.flip
    if @coin.save
      redirect_to root_path
    else
      render :index
    end
  end

  def reset
    Coin.destroy_all
    redirect_to root_path
  end

private

  def get_coins
    @heads = Coin.heads
    @tails = Coin.tails
    @last_flip = Coin.last
  end
end

app/controllers/ping_controller.rb
class PingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coins/index.html.slim
.box
  header
    h1 Coin Toss!
  section
    - if @coin.present? && @coin.errors.any?
      .callout.alert
        - @coin.errors.full_messages.each do |msg|
          p= msg

    .callout(class=(@last_flip.present? ? 'primary' : 'warning'))
      - if @last_flip.present?
        p You last flipped a #{@last_flip.to_s.pluralize}!
      - else
        p Why not flip a coin and test your luck?

    .row.collapse
      .small-12.medium-4.columns
        .callout
          h3= @heads
          p Heads!
      .small-12.medium-4.columns
        .action
          = link_to "Flip a coin!", coins_path, method: :post, class: :button
      .small-12.medium-4.columns
        .callout
          h3= @tails
          p Tails!

app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = action_cable_meta_tag
    = csrf_meta_tag

    title== content_for?(:title) ? yield(:title) : "Ansible Workshop"

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload"
    = javascript_include_tag "application", "data-turbolinks-track" => "reload"

  body
    header
      strong> Ansible Workshop
      i() (Step 9+)

    section
      == yield

app/views/ping/index.html.slim
h1 Passenger pre-start page
p This should only be visible from localhost